controllers/BugReportController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\web\Controller;
use app\models\AR\User;
use app\models\AR\BugReport;

class BugReportController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [
                            User::ROLE_ADMIN,
                            User::ROLE_TESTER,
                        ],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return mixed
     */
    public function actionAjaxCreate()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $model = new BugReport();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return [
                'success' => true,
            ];
        }

        return [
            'success' => false,
        ];
    }
}

controllers/GameController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ErrorAction;
use yii\db\Expression;
use app\models\AR\User;
use app\models\AR\Game;
use app\models\AR\Page;
use app\models\AR\Action;
use app\models\AR\Object;
use app\models\AR\Trigger;
use app\models\AR\GameObject;

class GameController extends Controller
{

    public $layout = 'game';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [
                            User::ROLE_ADMIN,
                            User::ROLE_TESTER,
                        ],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => ErrorAction::className(),
            ],
        ];
    }

    /**
     * Main game page
     *
     * @return string
     */
    public function actionIndex()
    {
        $game = Yii::$app->user->identity->game;

        if (!$game) {
            $game = new Game();
            $game->save();
        }

        return $this->render('index', [
            'game' => $game,
            'page_render' => $this->show(),
        ]);
    }

    public function actionNew($quantum = false)
    {
        if (Yii::$app->user->identity->game) {
            Yii::$app->user->identity->game->delete();
        }

        if ($quantum) {
            $game = new Game();
            $game->initQuantum();
            $game->save();
        }
        
        $this->redirect(['index']);
    }
    
    public function actionDrop($title)
    {
        $game = Game::getGameIdentity();
        $data = $game->getData();
        $function = Trigger::dropObject();
        $function($title);
        unset($data['only']);
        unset($data['links']);
        $game->setData($data);
        $game->save();
        return $this->show();
    }    
    
    public function actionBuy($item, $price, $trigger = null)
    {
        if ($trigger) {
            $trigger_model = new Trigger();
            $trigger_model->callback = $trigger;
            $trigger_model->exec();
        }

        $item = Object::byID($item);

        $game = Game::getGameIdentity();
        $game->link('objects', $item);

        $money = $game->money();
        $money->value -= $price;
        $money->save();

        return $this->actionMove($game->page_id);
    }

    public function actionDraw($suit, $quantity, $value = null)
    {
        $game = Game::getGameIdentity();
        $data = $game->getData();
        
        for ($i = 1; $i <= $quantity; $i++) {
            Game::getGameIdentity()->drawCard($suit, $value);
        }
        unset($data['drawFromDiscard']);
        unset($data['links']);
        unset($data['only']);
        $game->setData($data);
        $game->save();
        return $this->show();
    }

    public function actionGetkeyword($title)
    {
        $game = Game::getGameIdentity();
        $data = $game->getData();
        
        $item = Object::byTitle($title); 
        $game->link('objects', $item);
        
        unset($data['getKeyword']);
        unset($data['links']);
        unset($data['only']);
        
        $game->setData($data);
        $game->save();
        return $this->show();
    }

    public function actionSell($item, $price)
    {
        $game = Game::getGameIdentity();

        $money = $game->money();
        $money->value += $price;
        $money->save();

        $item_model = GameObject::find()
            ->where(['id' => $item])
            ->one();

        if (!$item_model) {
            $item_model = GameObject::find()
                ->where(['object_id' => $item])
                ->andWhere(['game_id' => $game->id])
                ->one();
        }

        if ($item_model->object->category == Object::$CATEGORY_CARD) {
            $game->discardCard($item_model->object->title, $item_model->value);
        } else {
            $item_model->delete();
        }

        return $this->actionMove($game->page_id);
    }
    
    public function actionDiscard($suit, $value, $drawAfter = false)
    {
        Game::getGameIdentity()->discardCard($suit, $value);
        $game = Game::getGameIdentity();
        $data = $game->getData();
        
        foreach ($data['links'] as $key => $link) {
            if ($link['url'] == Url::to([
                'game/discard',
                'value' => $value,
                'suit' => $suit,
                'drawAfter' => $drawAfter,
            ])) {
                unset($data['links'][$key]);
            }
        }
        
        $data['discard']--;

        if ($data['discard'] == 0) {
            unset($data['discard']);
            unset($data['links']);
            unset($data['only']);
        } else {
            if (count($data['links']) == 0) {
                unset($data['discard']);
            }

            $data['only'] = true;
            $data['links'][] = [
                'url' => Url::to([
                    'game/move',
                    'pageId' => 52,
                ]),
                'text' => 'Поражение',
                'active' => true,
            ];
        }
        
        if ($drawAfter) {
            $suits = Object::getCardSuits();

            foreach ($suits as $suit) {
                $cards = GameObject::find()
                    ->bySuit($suit)
                    ->byGame($game->id)
                    ->byPlace(GameObject::$CARD_PLACE_DECK)
                    ->all();

                if (count($cards) >= 2) {
                    $data['links'][] = [
                        'url' => Url::to([
                            'game/draw',
                            'suit' => $suit,
                            'quantity' => 2
                        ]),
                        'text' => 'Взять 2 карты масти ' . $cards[0]->object->text,
                        'active' => true,
                    ];
                }
            }

            if (isset($data['links'])) {
                $data['only'] = true;
            }
            
            $game->setData($data);
            $game->save();
        }

        $game->setData($data);
        $game->save();
        
        return $this->show();
    }

    /**
     * @return Page
     */
    public function resetQuantum()
    {
        return Page::find()
            ->joinWith('tags')
            ->where(['like', 'tag.title', 'Квантовый: первый круг'])
            ->orderBy(new Expression('rand()'))
            ->one();
    }
    
    public function show()
    {
        $game = Game::getGameIdentity();

        if ($game->page->triggersMulti) {
            foreach ($game->page->triggersMulti as $trigger) {
                if (($trigger->condition && $trigger->check()) || !$trigger->condition) {
                    $trigger->exec();
                }
            }
        }

        $game = Game::getGameIdentity();
        $data = $game->getData();

//        if (stristr($game->page->tagsNames, 'Квантовый: точка входа')) {
//            $startPage = Page::find()
//                ->joinWith('tags')
//                ->where(['like', 'tag.title', 'Квантовый: первый круг'])
//                ->orderBy(new Expression('rand()'))
//                ->one();
//
//            $data = (array) $game->getData();
//            unset($data['quantum']);
//
//            $data['links'][] = [
//                'url' => Url::to([
//                    'game/move',
//                    'pageId' => $startPage->id,
//                ]),
//                'text' => 'Точка отсчёта - начало Гонки',
//                'active' => true,
//            ];
//
//            $game->setData($data);
//            $game->save();
//        }

//        if (stristr($game->page->tagsNames, 'Квантовый: веха') && stristr($game->page->tagsNames, 'Квантовый: первый круг')) {
//            $data = Yii::$app->user->identity->game->getData();
//            $data['quantum']['visited'][] = $game->page->id;
//
//            $game->setData($data);
//            $game->save();
//        }
//
//        if (stristr($game->page->tagsNames, 'Квантовый: далее')) {
//            $data = $game->getData();
//
//            $nextPage = Page::find()
//                ->joinWith('tags')
//                ->where(['like', 'tag.title', 'Квантовый: первый круг'])
//                ->andWhere(['not in', 'page.id', $data['quantum']['visited']])
//                ->orderBy(new Expression('rand()'))
//                ->one();
//
//            if (!$nextPage && stristr($game->page->tagsNames, 'Квантовый: рекурсия')) {
//                $nextPage = $this->resetQuantum();
//                $data = Yii::$app->user->identity->game->getData();
//            }
//
//            if (!$nextPage) {
//                $nextPage = Page::find()
//                    ->joinWith('tags')
//                    ->where([
//                        'or',
//                        ['like', 'tag.title', 'Квантовый: второй круг'],
//                        ['like', 'tag.title', 'Квантовый: третий круг'],
//                    ])
//                    ->andWhere(['not in', 'page.id', $data['quantum']['visited']])
//                    ->orderBy(new Expression('rand()'))
//                    ->one();
//
//                $data['quantum']['visited'] = [];
//            }

views/game/_page.php
<?php

use yii\bootstrap\Html;
use yii\helpers\Url;
use app\models\AR\User;
use app\models\AR\Trigger;
use app\models\AR\GameObject;
use app\models\AR\BugReport;
use app\components\widgets\ActiveForm;
use dmstr\widgets\Alert;

/* @var $this yii\web\View */
/* @var $page app\models\AR\Page */

if (Yii::$app->user->identity->game) {
    $data = Yii::$app->user->identity->game->getData();
}

$bugReportModel = new BugReport;

$show_objects = true;

if ($page->id == 455) {
    $func = Trigger::checkObject();
    if ($func("Возврат в прошлое")) {
        $money->value = 0;
        $show_objects = false;
    }
}
?>

<?php if (Yii::$app->user->identity->role == User::ROLE_ADMIN): ?>
    <div style="margin-bottom: -10px; margin-top: 15px;">
        <?= Html::a('Редактировать страницу', ['/admin/page/update', 'id' => $page->id], [
            'target' => '_blank',
            'class' => 'btn btn-primary btn-xs',
        ]) ?>
    </div>
<?php endif; ?>

<div class="row">
    <div class="col-lg-9 col-md-8 col-sm-7">
        <div class="page-text">
            <div class="page-text-bg">
                <?= Alert::widget()?>
                <?= $page->text ?>
            </div>
        </div>
        <ul class="page-links">
            <?php foreach ($links as $link): ?>
                <?php
                $linkText = ($link['active'])
                    ? Html::a($link['text'], '#', ['data-url' => $link['url']])
                    : $link['text']
                ?>
                <li>
                    <?= Html::tag('div', $linkText, ['class' => 'page-link']) ?>
                </li>
            <?php endforeach;?>
        </ul>
    </div>

    <div class="col-lg-3 col-md-4 col-sm-5" style="color: rgb(159, 154, 255);">
        <h3>Деньги</h3>
        <?= $money->value ?> CR

        <?php if ($game->items && $show_objects): ?>
            <hr>
            <h3>Предметы</h3>
            <?php foreach ($game->items as $object): ?>
                <?= $object->text ?>
                <br>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if ($game->upgrades && $show_objects): ?>
            <hr>
            <h3>Улучшения</h3>
            <?php foreach ($game->upgrades as $object): ?>
                <?= $object->text ?>
                <br>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if ($game->keywords && $show_objects): ?>
            <hr>
            <h3>Ключевое слово</h3>
            <?php foreach ($game->keywords as $object): ?>
                <?= $object->text ?>
                <br>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if ($game->showMarkers && $show_objects): ?>
            <hr>
            <?php $markerColors = [
                'Черви' =>'#e01616',
                'Буби' =>'#ff9f0f',
                'Трефы' =>'#27a000',
                'Пики' =>'#2801ff',
                
            ];?>
            <?php foreach ($game->showMarkers as $object): ?>
            <span class="">
                <?= $object->object->text ?>                    
            </span>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="<?= $object->value?>" aria-valuemin="0" aria-valuemax="20" style="background-color:<?=$markerColors[$object->object->text]?>; width: <?= $object->value*5?>%;">
                </div>
            </div>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if ($game->hand && $show_objects): ?>
            <hr>
            <h3>Карты</h3>
            <?php $suit = ''; ?>
            <?php foreach ($game->hand as $card): ?>
                <?php if ($suit != $card->object->text): ?>
                    <?php if ($suit != ''): ?>
                        </ul>
                    <?php endif; ?>
                <?php $suit = $card->object->text; ?>
                <h4><?= $card->object->text ?></h4>
                <ul>
                <?php endif; ?>
                <li>
                    <?= GameObject::getCardValueLabels()[$card->value] ?>
                </li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <br>
    </div>
</div>

<div class="modal fade" id="bug-report-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <?php $form = ActiveForm::begin([
            'id' => 'bug-report-form',
            'action' => Url::to(['/bug-report/ajax-create']),
            'options' => ['class' => 'modal-content'],
        ]); ?>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4>Баг-репорт</h4>
            </div>
            <div class="modal-body">
                <?= $form->field($bugReportModel, 'message')->textarea(['rows' => 6]) ?>
                <?= $form->field($bugReportModel, 'page_id')->hiddenInput(['value' => $page->id])->label(false) ?>
                <?= $form->field($bugReportModel, 'user_id')->hiddenInput(['value' => Yii::$app->user->identity->id])->label(false) ?>
            </div>
            <div class="modal-footer">
                <?= Html::submitButton('Отправить', ['class' => 'btn btn-success']) ?>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/game/index.php
<?php

use yii\bootstrap\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $game app\models\AR\Game */

$this->title = 'SpaceRace';
?>

<div class="book">
    <h1 class="text-center">SpaceRace</h1>
    <?= Html::a('Новая игра', Url::to(['game/new']), [
        'class' => 'new-game',
    ]) ?>
    <?= Html::a('[Баг-репорт]', '#', [
        'class' => 'new-game',
        'style' => 'margin-left: 120px;',
        'data-toggle' => 'modal',
        'data-target' => '#bug-report-modal',
    ]) ?>
    <div class="page">
        <?= $page_render ?>
    </div>

</div>


